name: snackbar_mtl_example
description: Demonstrates using Metric Temporal Logic (MTL) for testing Snackbar behavior.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0" # Match workspace SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 # Or match counter_ltl version
  # Depend on the local mtl package
  temporal_logic_flutter:
    path: ../../packages/temporal_logic_flutter

dependency_overrides:
  temporal_logic_core:
    path: ../../packages/temporal_logic_core
  temporal_logic_mtl:
    path: ../../packages/temporal_logic_mtl

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Or match counter_ltl version
  fake_async: 1.3.2 # Pin to version required by flutter_test

flutter:
  uses-material-design: true
