name: temporal_logic_flutter
description: Flutter integration (TraceRecorder, Matchers) for temporal logic.
version: 0.0.1
homepage: https://github.com/rizumita/temporal_logic_flutter/tree/main/packages/temporal_logic_flutter # Replace with actual path if hosted

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Use path dependency to align with examples
  temporal_logic_core: any
  # Use path dependency for mtl as well if needed by this package
  temporal_logic_mtl: any
  collection: ^1.18.0
  clock: ^1.1.1 # Add clock package

# Add other dependencies here

# Add dev dependencies here, e.g.:
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1 # Keep consistent with core

resolution: workspace
