name: temporal_logic_flutter
description: Flutter integration (TraceRecorder, Matchers) for temporal logic.
version: 0.1.0
homepage: https://github.com/CAPHTECH/temporal_logic/tree/main/packages/temporal_logic_flutter
repository: https://github.com/CAPHTECH/temporal_logic

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Use path dependency to align with examples
  temporal_logic_core: ^0.1.0
  # Use path dependency for mtl as well if needed by this package
  temporal_logic_mtl: ^0.2.0
  collection: ^1.18.0
  clock: ^1.1.1 # Add clock package
  flutter_test:
    sdk: flutter

# Add other dependencies here

# Add dev dependencies here, e.g.:
dev_dependencies:
  lints: ^5.1.1 # Keep consistent with core
  fake_async: ^1.3.1 # Add fake_async for testing

resolution: workspace
