name: login_flow_ltl_example
description: An example demonstrating LTL verification for a login flow.
publish_to: "none" # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0" # Match workspace SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 # Or match counter_ltl version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  temporal_logic_flutter:
    path: ../../packages/temporal_logic_flutter

dependency_overrides:
  temporal_logic_core:
    path: ../../packages/temporal_logic_core
  temporal_logic_mtl:
    path: ../../packages/temporal_logic_mtl

flutter:
  uses-material-design: true
