name: temporal_logic_mtl
description: Metric Temporal Logic (MTL) extensions for temporal_logic_core.
version: 0.0.1
homepage: https://github.com/rizumita/temporal_logic_flutter/tree/main/packages/temporal_logic_mtl # Replace with actual path if hosted

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  temporal_logic_core: any # Resolved via workspace
  # test: ^1.24.0 # Moved to dev_dependencies

# Add other dependencies here if needed

# Add dev dependencies here, e.g.:
dev_dependencies:
  lints: ^5.1.1 # Align with temporal_logic_flutter
  test: ^1.24.0 # Test framework

resolution: workspace
