name: temporal_logic_core
description: Core LTL/MTL AST, evaluator, and builder DSL for Dart.
version: 0.0.1
homepage: https://github.com/rizumita/temporal_logic_flutter/tree/main/packages/temporal_logic_core # Replace with actual path if hosted

environment:
  sdk: ">=3.6.0 <4.0.0"

# Add dependencies here if needed
# dependencies:
#   meta: ^1.12.0

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1

resolution: workspace
