name: temporal_logic_core
description: Core LTL/MTL AST, evaluator, and builder DSL for Dart.
version: 0.1.0
homepage: https://github.com/CAPHTECH/temporal_logic/tree/main/packages/temporal_logic_core
repository: https://github.com/CAPHTECH/temporal_logic

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  meta: ^1.12.0

# Add dependencies here if needed
# dependencies:

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
