name: temporal_logic_core
description: Core LTL/MTL AST, evaluator, and builder DSL for Dart.
version: 0.0.1
homepage: https://github.com/rizumita/temporal_logic_flutter/tree/main/packages/temporal_logic_core # Replace with actual path if hosted

environment:
  sdk: ">=3.6.0 <4.0.0"

# Add dependencies here if needed
# dependencies:
#   meta: ^1.12.0

# Add dev dependencies here, e.g.:
# dev_dependencies:
#   test: ^1.24.0
#   lints: ^3.0.0

resolution: workspace
